// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200914100524_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Core.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ee4611dd-82b1-4c30-94e1-579c9b7b2820"),
                            IsDeleted = false,
                            Name = "Elektronik"
                        },
                        new
                        {
                            Id = new Guid("a837cf99-e02a-4d4a-9a7e-44f0b6166c24"),
                            IsDeleted = false,
                            Name = "Kırtasiye"
                        });
                });

            modelBuilder.Entity("Core.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("InnerBarcode")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5a87c22a-04e4-4053-8013-25b6e0fb80a1"),
                            CategoryId = new Guid("ee4611dd-82b1-4c30-94e1-579c9b7b2820"),
                            IsDeleted = false,
                            Name = "Monitor",
                            Price = 2000.50m,
                            Stock = 0
                        },
                        new
                        {
                            Id = new Guid("ed374727-ca96-4e4b-95e7-3921083f8528"),
                            CategoryId = new Guid("ee4611dd-82b1-4c30-94e1-579c9b7b2820"),
                            IsDeleted = false,
                            Name = "Klavye",
                            Price = 100.50m,
                            Stock = 0
                        },
                        new
                        {
                            Id = new Guid("6019a554-a60e-497f-8cf2-3d722ede7a8a"),
                            CategoryId = new Guid("ee4611dd-82b1-4c30-94e1-579c9b7b2820"),
                            IsDeleted = false,
                            Name = "Laptop",
                            Price = 4000.50m,
                            Stock = 0
                        },
                        new
                        {
                            Id = new Guid("d848782b-1968-4cc6-9f62-e50b1f389011"),
                            CategoryId = new Guid("ee4611dd-82b1-4c30-94e1-579c9b7b2820"),
                            IsDeleted = false,
                            Name = "Masaüstü",
                            Price = 5000.50m,
                            Stock = 0
                        },
                        new
                        {
                            Id = new Guid("786bf428-177a-4e94-bde5-64eb9ec67a9c"),
                            CategoryId = new Guid("a837cf99-e02a-4d4a-9a7e-44f0b6166c24"),
                            IsDeleted = false,
                            Name = "Kalem",
                            Price = 2000.50m,
                            Stock = 0
                        },
                        new
                        {
                            Id = new Guid("fa358af7-5709-4311-b0dc-f61f24af4923"),
                            CategoryId = new Guid("a837cf99-e02a-4d4a-9a7e-44f0b6166c24"),
                            IsDeleted = false,
                            Name = "Kitap",
                            Price = 2000.50m,
                            Stock = 0
                        });
                });

            modelBuilder.Entity("Core.Models.Product", b =>
                {
                    b.HasOne("Core.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
